FORMAT: 1A
HOST: https://api.acme.com

# PhxDocs API

A demo API for the PhoenixApiDocs project.


# Group User


## User [/api/users]

### List all users [GET]

Optional description that will be displayed in the documentation


::: note
Optional note that will be displayed in the documentation
:::


+ Parameters

+ Response 200
  {"data":[{"username":"john.doe12","name":"John Doe12","id":"10012","email":"john.doe-12@example.org"},{"username":"john.doe13","name":"John Doe13","id":"10013","email":"john.doe-13@example.org"},{"username":"john.doe14","name":"John Doe14","id":"10014","email":"john.doe-14@example.org"},{"username":"john.doe15","name":"John Doe15","id":"10015","email":"john.doe-15@example.org"},{"username":"john.doe16","name":"John Doe16","id":"10016","email":"john.doe-16@example.org"},{"username":"john.doe17","name":"John Doe17","id":"10017","email":"john.doe-17@example.org"},{"username":"john.doe18","name":"John Doe18","id":"10018","email":"john.doe-18@example.org"},{"username":"john.doe19","name":"John Doe19","id":"10019","email":"john.doe-19@example.org"},{"username":"john.doe20","name":"John Doe20","id":"10020","email":"john.doe-20@example.org"},{"username":"john.doe21","name":"John Doe21","id":"10021","email":"john.doe-21@example.org"}]}

